import { buildMetadata } from '@/lib/seo/metadata'

export const areasMetadata = buildMetadata({
  title: 'Calgary Service Areas | Victoria Park Nails & Spa',
  description:
    'Explore how Victoria Park Nails & Spa supports Victoria Park, Downtown, Beltline, Mission, Mount Royal, Inglewood, East Village, and Erlton with long-wear manicures, spa pedicures, extensions, massage, and waxing.',
  path: '/areas',
  keywords: [
    'nail salon Victoria Park Calgary',
    'nail salon Downtown Calgary',
    'nail salon Beltline Calgary',
    'nail salon Mission Calgary',
    'nail salon Mount Royal Calgary',
    'nail salon Inglewood Calgary',
    'nail salon East Village Calgary',
    'nail salon Erlton Calgary',
    'nail salon Calgary SE',
    'manicure downtown Calgary',
    'manicure Victoria Park',
    'pedicure Beltline Calgary',
    'pedicure Mission Calgary',
    'pedicure Inglewood Calgary',
    'gel nails downtown Calgary',
    'gel nails Victoria Park Calgary',
    'acrylic nails Victoria Park',
    'acrylic nails Beltline Calgary',
    'nail salon near Calgary Stampede',
    'nail salon near Saddledome Calgary',
    'Victoria Park nail spa',
    'Calgary nail salon',
    'nail services Calgary',
    'nail salon Calgary SE',
    'best nail salon Calgary',
    'nail art Calgary',
    'spa pedicure Calgary',
    'luxury nail salon Calgary',
    'nail salon 1st Street SE Calgary',
    'nail salon Stephen Avenue Calgary',
    'nail salon 17th Avenue Calgary',
    'nail salon 4th Street SW Calgary',
  ],
  openGraphDescription:
    'Discover our Calgary service areas and what nearby guests love most about Victoria Park Nails & Spa - from Victoria Park locals to Beltline creatives and East Village professionals.',
})
