export { AboutPage } from './about-page'
export { aboutMetadata } from './about.seo'
export * from './sections/hero'
export * from './sections/story'
export * from './sections/stats'
export * from './sections/values'
export * from './sections/location'
export * from './sections/philosophy'
export * from './sections/credentials'
export * from './sections/who-we-serve'
export * from './sections/cta'
